# -*- coding: utf-8 -*-
"""Aus Lektionslandkarte_Algebra_v5.docx erzeugt — nicht von Hand ändern.

170 Lektionen. Format:  "Nr": ([Voraussetzungen], "Titel")
"""

LEKTIONEN = {
    "1.1": ([], "Positive und negative Zahlen verstehen"),
    "1.2": (["1.1"], "Zahlen auf der Zahlengeraden"),
    "1.3": (["1.1"], "Vorzeichen und Operationszeichen unterscheiden"),
    "1.4": (["1.1"], "Strich- und Punktoperatoren erkennen"),
    "1.5": (["1.4"], "Addition mit positiven Zahlen"),
    "1.6": (["1.4"], "Subtraktion mit positiven Zahlen"),
    "1.7": (["1.5", "1.3"], "Addition positiver und negativer Zahlen"),
    "1.8": (["1.7"], "Addition zweier negativer Zahlen"),
    "1.9": (["1.6", "1.3"], "Subtraktion mit negativen Zahlen"),
    "1.10": (["1.4"], "Multiplikation mit positiven Zahlen"),
    "1.11": (["1.10", "1.3"], "Multiplikation mit unterschiedlichen Vorzeichen"),
    "1.12": (["1.11"], "Multiplikation zweier negativer Zahlen"),
    "1.13": (["1.10"], "Division mit positiven Zahlen"),
    "1.14": (["1.13", "1.11"], "Division mit unterschiedlichen Vorzeichen"),
    "1.15": (["1.14"], "Division zweier negativer Zahlen"),
    "1.16": (["1.8", "1.12"], "Punkt vor Strich ohne Klammern"),
    "1.17": (["1.15"], "Mehrere Punktoperationen"),
    "1.18": (["1.9"], "Mehrere Strichoperationen"),
    "1.19": (["1.16", "1.17", "1.18"], "Gemischte Punkt- und Strichoperationen"),
    "1.20": ([], "Gemischt: alles aus Kapitel 1 kombiniert"),
    "2.1": (["1.13"], "Brüche verstehen"),
    "2.2": (["2.1"], "Kürzen und Erweitern"),
    "2.3": (["2.1"], "Addition bei gleichem Nenner"),
    "2.4": (["2.3"], "Subtraktion bei gleichem Nenner"),
    "2.5": (["2.2"], "Hauptnenner bestimmen (kgV)"),
    "2.6": (["2.4", "2.5"], "Addition und Subtraktion bei ungleichen Nennern"),
    "2.7": (["2.6"], "Brüche mit ganzen Zahlen addieren"),
    "2.8": (["2.7"], "Brüche mit ganzen Zahlen subtrahieren"),
    "2.9": (["2.2", "1.10"], "Multiplikation von Brüchen"),
    "2.10": (["2.9"], "Division von Brüchen"),
    "2.11": (["2.9"], "Brüche mal und durch ganze Zahlen"),
    "2.12": (["2.10"], "Doppelbrüche"),
    "2.13": ([], "Gemischt: alles aus Kapitel 2 kombiniert"),
    "3.1": (["1.19"], "Bedeutung von Variablen"),
    "3.2": (["3.1"], "Variablen als Platzhalter für Zahlen"),
    "3.3": (["3.2"], "Einsetzen von Zahlen in Terme"),
    "3.4": (["3.3", "1.5"], "Addieren gleichartiger Variablen"),
    "3.5": (["3.3", "1.6"], "Subtrahieren gleichartiger Variablen"),
    "3.6": (["3.3", "1.10"], "Multiplizieren gleichartiger Variablen"),
    "3.7": (["3.4"], "Addieren unterschiedlicher Variablen"),
    "3.8": (["3.5"], "Subtrahieren unterschiedlicher Variablen"),
    "3.9": (["3.6"], "Multiplizieren unterschiedlicher Variablen"),
    "3.10": (["3.4", "3.7"], "Terme mit Zahlen und Variablen"),
    "3.11": (["3.10"], "Terme vereinfachen mit Zahlen und Variablen"),
    "3.12": ([], "Gemischt: alles aus Kapitel 3 kombiniert"),
    "4.1": (["3.11"], "Gleichartige Terme erkennen"),
    "4.2": (["4.1", "3.4"], "Addition gleichartiger Terme"),
    "4.3": (["4.1", "3.5"], "Subtraktion gleichartiger Terme"),
    "4.4": (["4.2"], "Mehrere gleichartige Terme addieren"),
    "4.5": (["4.3", "4.4"], "Mehrere gleichartige Terme gemischt"),
    "4.6": (["4.5", "3.10"], "Gleichartige Terme mit Zahlen"),
    "4.7": (["4.1", "3.7"], "Unterschiedliche Variablen erkennen"),
    "4.8": (["4.6", "4.7"], "Term mit mehreren Teilen vereinfachen"),
    "4.9": (["4.7", "3.9"], "Produkte als gleichartige Terme erkennen"),
    "4.10": ([], "Gemischt: alles aus Kapitel 4 kombiniert"),
    "5.1": (["3.9"], "Zahl mal Variable"),
    "5.2": (["3.6"], "Variable mal Variable (gleich)"),
    "5.3": (["3.9"], "Variable mal Variable (ungleich)"),
    "5.4": (["5.2", "5.3"], "Multiplikation mehrerer Variablen"),
    "5.5": (["5.1"], "Multiplikation von Zahl und Term"),
    "5.6": (["5.5", "5.3"], "Multiplikation von zwei Termen"),
    "5.7": (["5.6", "5.2"], "Vereinfachen von Produkten"),
    "5.8": (["5.7", "1.12"], "Produkte mit Vorzeichen und drei Faktoren"),
    "5.9": ([], "Gemischt: alles aus Kapitel 5 kombiniert"),
    "6.1": (["5.7", "4.8"], "Reihenfolge in Termen mit Variablen erkennen"),
    "6.2": (["6.1", "1.16"], "Punkt vor Strich mit einer Variablen"),
    "6.3": (["6.2", "5.7"], "Punkt vor Strich mit mehreren Variablen"),
    "6.4": (["6.3", "1.12"], "Vorzeichen und Punkt vor Strich kombiniert"),
    "6.5": (["6.4", "4.9"], "Nach dem Ausrechnen: gleichartig oder nicht?"),
    "6.6": (["5.4", "1.17"], "Mehrere Punktoperationen in einem Term"),
    "6.7": (["6.5", "6.6"], "Längere Terme mit Punkt und Strich"),
    "6.8": ([], "Gemischt: alles aus Kapitel 6 kombiniert"),
    "7.1": (["1.10"], "Bedeutung von Potenzen"),
    "7.2": (["7.1", "5.2"], "Potenzen mit Variablen"),
    "7.3": (["7.1", "1.19"], "Potenz vor Punkt vor Strich"),
    "7.4": (["7.3", "1.12"], "Potenzen mit negativer Basis"),
    "7.5": (["7.2"], "Multiplikation von Potenzen"),
    "7.6": (["7.5"], "Division von Potenzen"),
    "7.7": (["7.2", "4.1"], "Potenzen und Strichoperatoren"),
    "7.8": (["7.5"], "Potenz einer Potenz"),
    "7.9": (["7.8", "5.7"], "Potenz eines Produkts erkennen"),
    "7.10": (["7.9"], "Potenzen mit mehreren Variablen"),
    "7.11": ([], "Gemischt: alles aus Kapitel 7 kombiniert"),
    "8.1": (["7.8"], "Wurzel als Gegenteil der Potenz"),
    "8.2": (["8.1"], "Quadratwurzel von Quadratzahlen"),
    "8.3": (["8.2", "1.16"], "Wurzel aus einer Summe: erst die Klammer"),
    "8.4": (["8.2"], "Wurzeln addieren und subtrahieren"),
    "8.5": (["8.2"], "Wurzeln multiplizieren und dividieren"),
    "8.6": (["8.5"], "Wurzelgesetz bei Division anwenden"),
    "8.7": (["8.3"], "Warum √(a+b) nicht √a + √b ist"),
    "8.8": (["8.5"], "Wurzelgesetz bei Produkten"),
    "8.9": (["8.8", "7.9"], "Wurzel aus Produkt mit Variable"),
    "8.10": ([], "Gemischt: alles aus Kapitel 8 kombiniert"),
    "9.1": (["5.1", "1.13"], "Term durch Zahl dividieren"),
    "9.2": (["9.1", "3.6"], "Term durch Variable dividieren"),
    "9.3": (["9.2", "5.7"], "Einfaches Monom durch Monom"),
    "9.4": (["9.3", "7.10"], "Monome mit Potenzen dividieren"),
    "9.5": (["9.4", "2.1"], "Division als Bruch schreiben"),
    "9.6": (["9.5", "6.7"], "Division in längeren Termen einordnen"),
    "9.7": ([], "Gemischt: alles aus Kapitel 9 kombiniert"),
    "10.1": (["1.19"], "Klammertypen erkennen"),
    "10.2": (["10.1", "1.18"], "Klammern mit nur Strichoperationen"),
    "10.3": (["10.2"], "Pluszeichen vor der Klammer"),
    "10.4": (["10.3", "1.9"], "Minus vor der Klammer"),
    "10.5": (["10.4", "1.12"], "Negative Zahl vor der Klammer"),
    "10.6": (["10.4"], "Minus vor Klammer mit mehreren Termen"),
    "10.7": (["10.1", "1.17"], "Klammern mit nur Punktoperationen"),
    "10.8": (["10.7", "1.16"], "Strich vor Klammer, Punkt in der Klammer"),
    "10.9": (["10.8"], "Punkt vor Klammer, Strich in der Klammer"),
    "10.10": (["10.9", "10.6"], "Mehrere Operationen in der Klammer"),
    "10.11": (["10.10"], "Punktoperation ausserhalb der Klammer"),
    "10.12": (["10.3", "4.8"], "Klammern mit Variablen auflösen"),
    "10.13": (["10.12", "10.4"], "Minus vor Klammer mit Variablen"),
    "10.14": (["10.13", "4.6"], "Zahlen und Variablen gemischt"),
    "10.15": (["10.13"], "Mehrere Klammern hintereinander"),
    "10.16": (["10.11", "7.4"], "Klammer mit negativem Ergebnis quadrieren"),
    "10.17": ([], "Gemischt: alles aus Kapitel 10 kombiniert"),
    "11.1": (["10.9", "5.5"], "Zahl mal Klammer"),
    "11.2": (["11.1", "10.4"], "Multiplikation mit Subtraktion in der Klammer"),
    "11.3": (["11.1"], "Mehrere Terme in der Klammer"),
    "11.4": (["11.3", "5.6"], "Variable mal Klammer"),
    "11.5": (["11.4", "4.8"], "Kombination mit gleichartigen Termen"),
    "11.6": (["11.5"], "Vereinfachen nach dem Ausmultiplizieren"),
    "11.7": (["11.2", "10.5"], "Negative Zahl mal Klammer"),
    "11.8": (["11.7", "11.4"], "Variable mit Minus davor mal Klammer"),
    "11.9": (["11.7", "2.9"], "Bruch mal Klammer"),
    "11.10": ([], "Gemischt: alles aus Kapitel 11 kombiniert"),
    "12.1": (["11.6"], "Gemeinsame Faktoren erkennen"),
    "12.2": (["12.1"], "Gemeinsame Zahl ausklammern"),
    "12.3": (["12.1", "5.3"], "Gemeinsame Variable ausklammern"),
    "12.4": (["12.2", "12.3"], "Zahl und Variable zusammen ausklammern"),
    "12.5": (["12.4", "7.2"], "Ausklammern mit Potenzen"),
    "12.6": (["12.5", "7.10"], "Ausklammern mit mehreren Variablen"),
    "12.7": (["12.6"], "Dreigliedrige Terme faktorisieren"),
    "12.8": (["12.7", "11.4"], "Prüfen, ob vollständig ausgeklammert wurde"),
    "12.9": ([], "Gemischt: alles aus Kapitel 12 kombiniert"),
    "13.1": (["3.11"], "Bedeutung einer Gleichung"),
    "13.2": (["13.1"], "Äquivalenzumformungen"),
    "13.3": (["13.2", "1.9"], "Gleichung durch Subtraktion lösen"),
    "13.4": (["13.2", "1.13"], "Gleichung durch Division lösen"),
    "13.5": (["13.4", "11.6"], "Gleichungen mit Klammern"),
    "13.6": (["13.5", "4.8"], "Variablen auf beiden Seiten"),
    "13.7": (["13.6", "11.7"], "Klammern auf beiden Seiten"),
    "13.8": (["13.7", "3.3"], "Probe durchführen"),
    "13.9": (["13.4", "2.2"], "Lösung als gekürzter Bruch oder Dezimalzahl"),
    "13.10": ([], "Gemischt: alles aus Kapitel 13 kombiniert"),
    "14.1": (["2.1", "3.10"], "Bruchterme verstehen"),
    "14.2": (["14.1", "2.2"], "Bruchterme erweitern"),
    "14.3": (["14.2", "12.1"], "Nur Faktoren kürzen, nie Summanden"),
    "14.4": (["14.3", "9.5"], "Bruchterme mit Monomen kürzen"),
    "14.5": (["14.4", "12.5"], "Kürzen nach dem Ausklammern"),
    "14.6": (["14.2", "2.3"], "Bruchterme addieren bei gleichem Nenner"),
    "14.7": (["14.6", "10.6", "2.6"], "Klammer im Zähler mit Minus davor"),
    "14.8": (["14.7", "2.7"], "Ganze Terme auf den Hauptnenner bringen"),
    "14.9": (["14.4", "2.9"], "Bruchterme multiplizieren"),
    "14.10": (["14.9", "2.10"], "Bruchterme dividieren"),
    "14.11": (["14.10", "2.12"], "Doppelbruch mit Variablen auflösen"),
    "14.12": ([], "Gemischt: alles aus Kapitel 14 kombiniert"),
    "15.1": (["13.4", "14.1"], "Gleichung mit einem Bruch"),
    "15.2": (["15.1", "2.5"], "Hauptnenner beider Seiten bestimmen"),
    "15.3": (["15.2", "13.6"], "Jeden Summanden mit dem Hauptnenner malnehmen"),
    "15.4": (["15.3", "14.7"], "Term im Zähler"),
    "15.5": (["15.4"], "Zwei Brüche auf einer Seite, gleich null"),
    "15.6": (["15.5", "11.9"], "Bruch mal Klammer in einer Gleichung"),
    "15.7": (["15.6"], "Term im Nenner (ohne x)"),
    "15.8": (["15.7"], "x im Nenner"),
    "15.9": ([], "Gemischt: alles aus Kapitel 15 kombiniert"),
    "16.1": ([], "Gemischte Termvereinfachung über mehrere Kapitel"),
    "16.2": ([], "Gemischte Gleichungen"),
    "16.3": ([], "Simulation des Erhebungstests"),
}
